// <auto-generated />
using System;
using HackYeah_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HackYeah_Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251004215904_InitiateBunker")]
    partial class InitiateBunker
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("HackYeah_Backend.Models.Bunker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Building")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<float>("x")
                        .HasColumnType("REAL");

                    b.Property<float>("y")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Bunkers");
                });

            modelBuilder.Entity("HackYeah_Backend.Models.LocationRcb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RcbId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RcbId");

                    b.ToTable("LocationsRcb");
                });

            modelBuilder.Entity("HackYeah_Backend.Models.Rcb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rcbs");
                });

            modelBuilder.Entity("HackYeah_Backend.Models.TagRcb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RcbId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RcbId");

                    b.ToTable("TagsRcb");
                });

            modelBuilder.Entity("HackYeah_Backend.Models.LocationRcb", b =>
                {
                    b.HasOne("HackYeah_Backend.Models.Rcb", "Rcb")
                        .WithMany("Locations")
                        .HasForeignKey("RcbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rcb");
                });

            modelBuilder.Entity("HackYeah_Backend.Models.TagRcb", b =>
                {
                    b.HasOne("HackYeah_Backend.Models.Rcb", "Rcb")
                        .WithMany("Tags")
                        .HasForeignKey("RcbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rcb");
                });

            modelBuilder.Entity("HackYeah_Backend.Models.Rcb", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
